{
    "type": "interests",
    "options": {
        "lifestyle": [
            "Cinema",
            "Clubbing",
            "Shopping",
            "Wine tasting",
            "Food tasting",
            "Casino games",
            "Collecting",
            "Travelling",
            "Exploration",
            "Yoga",
            "Meditation",
            "Martial Arts",
            "Feng Shui"
        ],
        "actvities": [
            "Reading",
            "Birdwatching",
            "Photography",
            "Cloudwatching",
            "Stargazing",
            "Playing cards",
            "Tarot card reading",
            "Board games",
            "Watching movies",
            "Chess",
            "Bowling",
            "Billiards",
            "Table tennis",
            "Pottery",
            "Scrapbooking"
        ],
        "creative-hobbies": [
            "Filmmaking",
            "Cooking",
            "Painting",
            "Graffiti",
            "Creative writing",
            "Dancing",
            "Choreographing",
            "Singing",
            "Composing",
            "Sculpting",
            "Model building",
            "Interior decorating",
            "Jewelry-making"
        ],
        "sports-based": [
            "Basketball",
            "American football",
            "Baseball",
            "Ice hockey",
            "Soccer",
            "Volleyball",
            "Scuba diving",
            "River rafting",
            "Bungee jumping",
            "Skiing",
            "Trekking",
            "Ice skating",
            "Surfing",
            "Auto racing",
            "Gymnastics",
            "Hunting",
            "Bodybuilding",
            "Running",
            "Jumpingrope",
            "Swimming"
        ],
        "specific-interests": [
            "Robotics",
            "Computer games",
            "Social networking",
            "Programming",
            "Animations",
            "Gardening",
            "Recycling"
        ]
    }
}
